version: '3'
services:
  mysql:
    image: "docker.io/mysql:8.0"
    container_name: mysql01
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: Goobai!1
    ports:
      - "3307:3306"

    volumes:
      - /home/services/mysql/data:/var/lib/mysql
      - /home/services/mysql/conf/my.conf:/etc/my.conf
      - /home/services/mysql/log:/var/log
